### ISSUE TITLE
The POM for com.tunyk.mvn.plugins.htmlcompressor:htmlcompressor-maven-plugin:jar:1.4-SNAPSHOT is missing, no dependency information available

### ISSUE THREAD

**Issue by kevinfaguiar** [alextunyk/htmlcompressor-maven-plugin#11]
My pom:

>  <plugin>
		        <groupId>com.tunyk.mvn.plugins.htmlcompressor</groupId>
	               <artifactId>htmlcompressor-maven-plugin</artifactId>
	                <version>1.4-SNAPSHOT</version>
		        <configuration>
	                     <goalPrefix>htmlcompressor</goalPrefix>
	                 </configuration>
		      </plugin>

**Comment by kevinfaguiar** [comment]
This occurs when maven building with htmlcompressor:html goal

**Comment by hazendaz** [comment]
We don't release the snapshot. If you are trying to use the snapshot you need to build the project yourself using 'mvn clean install' so that it installs locally for you.  The project builds without issue.  I would suggest cloning the project, running a build of it then going from there.  If you want to use the snapshot in a production style mode (possibly in corporate environment), at the moment you will need to upload it youreself into your setup.  I otherwise do not feel this is a valid condition here so I'm closing this.  If you are attempting to use what we have for a release, please use 1.3.

**Comment by hazendaz** [comment]
We plan to start releasing sonatype snapshots in near future and will make a link available to it off the readme.  I have reopened this for tracking towards that goal.  Primarly this will get turned on once I get my release access on sonatype which I'm submitting today.

**Comment by hazendaz** [comment]
@kevinfaguiar Version 1.4.0 has been released.  I'm closing this issue.  Sorry for long delay.  You will need to also change group id to 'com.github.hazendaz.maven'.  Everything else is the same.  It is not showing in central at time of this writing but will be available within 2 hours.  Please see our 'pom.xml' for details and upper commits for the same.  Thanks!
